package voxgig.thesmsworkssdk.core

import java.util.{Map => JMap}

import voxgig.thesmsworkssdk.utility.Json

// Static SDK configuration and by-name feature construction.
object Config {

  def makeConfig(): JMap[String, Object] =
    Json.parse(configJson()).asInstanceOf[JMap[String, Object]]

  def makeFeature(name: String): Feature = name match {
    case "test" => new voxgig.thesmsworkssdk.feature.TestFeature()
    case _ => new voxgig.thesmsworkssdk.feature.BaseFeature()
  }

  private def configJson(): String = {
    val b = new StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"Thesmsworks\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://api.thesmsworks.co.uk/v1\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"batch\": {},")
    b.append("   \"batch_message\": {},")
    b.append("   \"credit\": {},")
    b.append("   \"flash\": {},")
    b.append("   \"message\": {},")
    b.append("   \"one_time_password\": {},")
    b.append("   \"schedule\": {},")
    b.append("   \"swagger\": {},")
    b.append("   \"util\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"batch\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"batch\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"batchid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/batch/{batchid}\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"batchid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"batch_message\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ai\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$BOOLEAN`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"content\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"deliveryreporturl\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"destination\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"schedule\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sender\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"tag\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ttl\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"validity\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 8")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"batch_message\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/any\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"any\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/send\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 2")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"batchid\",")
    b.append("          \"orig\": \"batchid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/batches/schedule/{batchid}\",")
    b.append("       \"parts\": [")
    b.append("        \"batches\",")
    b.append("        \"schedule\",")
    b.append("        \"{batchid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"batchid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"remove\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"schedule\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"credit\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"credit\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/credits/balance\",")
    b.append("       \"parts\": [")
    b.append("        \"credits\",")
    b.append("        \"balance\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"balance\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"flash\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"flash\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"message\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ai\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$BOOLEAN`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"content\",")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"credit\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"deliveryreporturl\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"destination\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": false,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"from\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"keyword\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 6")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"limit\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 7")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"metadata\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 8")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"responseemail\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$ARRAY`\",")
    b.append("     \"index$\": 9")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"schedule\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 10")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sender\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"req\": false,")
    b.append("       \"type\": \"`$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 11")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"skip\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 12")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"status\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 13")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"tag\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 14")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"to\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 15")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"ttl\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 16")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"unread\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$BOOLEAN`\",")
    b.append("     \"index$\": 17")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"validity\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 18")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"message\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/flash\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"flash\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"flash\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"schedule\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/send\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"send\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 2")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 3")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages/failed\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"failed\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"failed\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 4")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages/inbox\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"inbox\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"inbox\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 5")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/messages/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"messageid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/messages/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"schedule\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/messages/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"messageid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"messageid\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/messages/schedule/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"schedule\",")
    b.append("        \"{messageid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"messageid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"remove\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"schedule\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"one_time_password\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"destination\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 0")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"length\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 1")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"metadata\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$OBJECT`\",")
    b.append("     \"index$\": 2")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"passcode\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 3")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"sender\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 4")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"template\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$STRING`\",")
    b.append("     \"index$\": 5")
    b.append("    },")
    b.append("    {")
    b.append("     \"active\": true,")
    b.append("     \"name\": \"validity\",")
    b.append("     \"req\": false,")
    b.append("     \"type\": \"`$NUMBER`\",")
    b.append("     \"index$\": 6")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"one_time_password\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/otp/send\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/otp/verify\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"verify\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"create\"")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"messageid\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/otp/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"{messageid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"messageid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"otp\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"schedule\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"schedule\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"swagger\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"swagger\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"util\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"util\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"active\": true,")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"errorcode\",")
    b.append("          \"orig\": \"errorcode\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`$STRING`\",")
    b.append("          \"index$\": 0")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/utils/errors/{errorcode}\",")
    b.append("       \"parts\": [")
    b.append("        \"utils\",")
    b.append("        \"errors\",")
    b.append("        \"{errorcode}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"errorcode\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 0")
    b.append("      },")
    b.append("      {")
    b.append("       \"active\": true,")
    b.append("       \"args\": {},")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/utils/test\",")
    b.append("       \"parts\": [")
    b.append("        \"utils\",")
    b.append("        \"test\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"$action\": \"test\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       },")
    b.append("       \"index$\": 1")
    b.append("      }")
    b.append("     ],")
    b.append("     \"key$\": \"load\"")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"error\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    b.toString
  }
}
