-- Thesmsworks SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

namespace Batch
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "batch" m co
end Batch

namespace Batch_message
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "batch_message" d co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "batch_message" m co
end Batch_message

namespace Credit
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "credit" m co
end Credit

namespace Flash
end Flash

namespace Message
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "message" d co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "message" m co
  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c "message" m co
end Message

namespace One_time_password
  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c "one_time_password" d co
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "one_time_password" m co
end One_time_password

namespace Schedule
end Schedule

namespace Swagger
end Swagger

namespace Util
  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c "util" m co
end Util

