-- Thesmsworks SDK — documentation Haskell-examples structural gate.
--
-- Validates that every fenced Haskell code block in the SDK docs (the root
-- README.md, the per-language README.md, and REFERENCE.md) is present,
-- non-empty, and has balanced delimiters. Missing docs are tolerated (a run
-- may generate a subset of phases), so this gate never breaks the shared
-- runner. See ReadmeExamplesTest_haskell for why this is a structural gate
-- rather than a full compile harness. Generated by @voxgig/sdkgen.

{-# LANGUAGE ScopedTypeVariables #-}

module TReadmeExamples (tests) where

import Control.Exception (SomeException, evaluate, try)
import Control.Monad (forM_)

import Testutil (Counters, runTest)


-- True for the whitespace characters we trim: space, tab, carriage return.
isWs :: Char -> Bool
isWs ch = let n = fromEnum ch in n == 32 || n == 9 || n == 13


-- Trim leading/trailing whitespace from a line.
trimWs :: String -> String
trimWs = f . f
  where f = reverse . dropWhile isWs


-- Read a doc file, tolerating absence (returns "" when missing/unreadable).
readDoc :: FilePath -> IO String
readDoc path = do
  r <- try (do s <- readFile path; _ <- evaluate (length s); pure s)
         :: IO (Either SomeException String)
  pure (either (const "") id r)


-- Extract the body of every fenced Haskell block from markdown. The fence
-- marker (three backticks) is built from its char code so this source stays
-- backtick-free.
haskellBlocks :: String -> [String]
haskellBlocks src = go (lines src)
  where
    fence3 = replicate 3 (toEnum 96 :: Char)
    fenceHs = fence3 ++ "haskell"
    go [] = []
    go (l : ls)
      | trimWs l == fenceHs =
          let (blk, rest) = break (\x -> trimWs x == fence3) ls
          in unlines blk : go (drop 1 rest)
      | otherwise = go ls


-- Balanced (), [], {} ignoring the contents of double-quoted string literals.
-- The generated snippets never embed an escaped quote inside a string.
balanced :: String -> Bool
balanced = go False (0 :: Int)
  where
    go inStr d [] = not inStr && d == 0
    go inStr d (c : cs)
      | c == '"'                          = go (not inStr) d cs
      | inStr                             = go inStr d cs
      | c == '(' || c == '[' || c == '{'  = go inStr (d + 1) cs
      | c == ')' || c == ']' || c == '}'  =
          if d <= 0 then False else go inStr (d - 1) cs
      | otherwise                         = go inStr d cs


-- The three documents held to the gate, tagged by human label.
docs :: [(String, FilePath)]
docs =
  [ ("root README", "../README.md")
  , ("haskell README", "README.md")
  , ("haskell REFERENCE", "REFERENCE.md")
  ]


tests :: Counters -> IO ()
tests c =
  forM_ docs (\(label, path) -> do
    src <- readDoc path
    let blocks = haskellBlocks src
    forM_ (zip [1 :: Int ..] blocks) (\(i, blk) ->
      runTest c (label ++ " haskell block " ++ show i ++ " well-formed")
        (pure (not (null (trimWs blk)) && balanced blk))))
