// Structural gate over every ```rust block in the Thesmsworks SDK
// docs (root README.md, rust/README.md, rust/REFERENCE.md). Generated by
// @voxgig/sdkgen — do not edit by hand.
//
// Validates that each documented rust block is present, non-empty, and has
// balanced delimiters. Missing docs are tolerated. See ReadmeExamplesTest_rust
// for why this is a structural gate rather than a full compile harness.

use std::fs;
use std::path::PathBuf;

// Extract the body of every ```rust ... ``` fenced block from markdown.
fn extract_rust_blocks(md: &str) -> Vec<String> {
    let mut blocks: Vec<String> = Vec::new();
    let mut in_block = false;
    let mut cur: Vec<&str> = Vec::new();
    for line in md.lines() {
        let trimmed = line.trim();
        if !in_block {
            if trimmed == "```rust" {
                in_block = true;
                cur = Vec::new();
            }
            continue;
        }
        if trimmed == "```" {
            blocks.push(cur.join("\n"));
            in_block = false;
            continue;
        }
        cur.push(line);
    }
    blocks
}

// Balanced (), [], {} outside of string literals. Naive quote toggle: the
// generated snippets never embed an escaped quote inside a string.
fn is_balanced(block: &str) -> bool {
    let mut in_str = false;
    let mut depth: i32 = 0;
    for c in block.chars() {
        if c == '"' {
            in_str = !in_str;
            continue;
        }
        if in_str {
            continue;
        }
        match c {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => {
                depth -= 1;
                if depth < 0 {
                    return false;
                }
            }
            _ => {}
        }
    }
    depth == 0 && !in_str
}

#[test]
fn readme_rust_snippets_wellformed() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let docs: [(&str, PathBuf); 3] = [
        ("root README", manifest.join("..").join("README.md")),
        ("rust/README", manifest.join("README.md")),
        ("rust/REFERENCE", manifest.join("REFERENCE.md")),
    ];

    let mut total_blocks = 0usize;
    for (label, path) in docs.iter() {
        let src = match fs::read_to_string(path) {
            Ok(s) => s,
            Err(_) => continue, // doc not generated in this run — tolerate
        };
        let blocks = extract_rust_blocks(&src);
        for (i, block) in blocks.iter().enumerate() {
            assert!(
                !block.trim().is_empty(),
                "{}: rust block {} is empty",
                label,
                i + 1
            );
            assert!(
                is_balanced(block),
                "{}: rust block {} has unbalanced delimiters:\n{}",
                label,
                i + 1,
                block
            );
            total_blocks += 1;
        }
    }

    assert!(
        total_blocks > 0,
        "no rust code blocks found in any README/REFERENCE doc"
    );
}
