// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Thesmsworks"),
      "slug", v_str("thesmsworks"),
      "version", v_str("0.0.2"),
      "target", v_str("c")),
    "feature", cmap(8,
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://api.thesmsworks.co.uk/v1"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(9,
        "batch", v_map(),
        "batch_message", v_map(),
        "credit", v_map(),
        "flash", v_map(),
        "message", v_map(),
        "one_time_password", v_map(),
        "schedule", v_map(),
        "swagger", v_map(),
        "util", v_map()),
      "auth", cmap(1,
        "prefix", v_str(""))),
    "entity", cmap(9,
      "batch", cmap(5,
        "fields", clist(1,
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("batch"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("batchid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/batch/{batchid}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "batchid", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("batch"),
                  v_str("{id}")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "batch_message", cmap(4,
        "fields", clist(9,
          cmap(3,
            "name", v_str("ai"),
            "short", v_str("Used to determine whether The SMS Works AI Optimiser should be used in the event that the message is just longer than the 1 or 2 credit boundary."),
            "type", v_str("`$BOOLEAN`")),
          cmap(4,
            "name", v_str("content"),
            "req", v_bool(true),
            "short", v_str("Message to send to the recipient"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("deliveryreporturl"),
            "short", v_str("The url to which we should POST delivery reports to for this message."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("destinations"),
            "req", v_bool(true),
            "short", v_str("Telephone numbers of each of the recipients"),
            "type", v_str("`$ARRAY`")),
          cmap(3,
            "name", v_str("schedule"),
            "short", v_str("Date-time at which to send the batch."),
            "type", v_str("`$STRING`")),
          cmap(4,
            "name", v_str("sender"),
            "req", v_bool(true),
            "short", v_str("The sender of the message."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("tag"),
            "short", v_str("An identifying label for the message, which you can use to filter and report on messages you've sent later."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("ttl"),
            "short", v_str("The number of minutes before the delivery report is deleted."),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("validity"),
            "short", v_str("The optional number of minutes to attempt delivery before the message is marked as EXPIRED."),
            "type", v_str("`$NUMBER`"))),
        "name", v_str("batch_message"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(3,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/batch/any"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("any"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("batch"),
                  v_str("any"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/batch/schedule"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("schedule"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("batch"),
                  v_str("schedule"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/batch/send"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("batch")),
                  cmap(1,
                    "lit", v_str("send"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("batch"),
                  v_str("send"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("batchid"),
                      "orig", v_str("batchid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/batches/schedule/{batchid}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("batches")),
                  cmap(1,
                    "lit", v_str("schedule")),
                  cmap(1,
                    "var", v_str("batchid"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("batchid"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("batches"),
                  v_str("schedule"),
                  v_str("{batchid}")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("schedule"))))),
      "credit", cmap(4,
        "fields", v_list(),
        "name", v_str("credit"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/credits/balance"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("credits")),
                  cmap(1,
                    "lit", v_str("balance"))),
                "select", cmap(1,
                  "$action", v_str("balance")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("credits"),
                  v_str("balance")))))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "flash", cmap(4,
        "fields", v_list(),
        "name", v_str("flash"),
        "op", v_map(),
        "relations", cmap(1,
          "ancestors", v_list())),
      "message", cmap(5,
        "fields", clist(12,
          cmap(3,
            "name", v_str("credits"),
            "short", v_str("The number of credits used on the message."),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("destination"),
            "short", v_str("The phone number of the recipient."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("from"),
            "short", v_str("The date-time from which you would like matching messages"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("id"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("keyword"),
            "short", v_str("The keyword used in the inbound message"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("limit"),
            "short", v_str("The maximum number of messages that you would like returned in this call."),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("metadata"),
            "short", v_str("An array of objects containing metadata key/value pairs that have been saved on messages."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("sender"),
            "short", v_str("The sender of the message (this can be the configured sender name for an outbound message or the senders phone number for an inbound message)."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("skip"),
            "short", v_str("The number of results you would like to ignore before returning messages."),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("status"),
            "short", v_str("The status of the messages you would like returned (either 'SENT', 'DELIVERED', 'EXPIRED', 'UNDELIVERABLE', 'REJECTED' or 'INCOMING')"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("to"),
            "short", v_str("The date-time to which you would like matching messages"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("unread"),
            "short", v_str("In queries for incoming messages ('status' is 'INCOMING'), specify whether you explicitly want unread messages (true) or read messages (false)."),
            "type", v_str("`$BOOLEAN`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("message"),
        "op", cmap(3,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(6,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/message/flash"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("message")),
                  cmap(1,
                    "lit", v_str("flash"))),
                "select", cmap(1,
                  "$action", v_str("flash")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("message"),
                  v_str("flash"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/message/schedule"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("message")),
                  cmap(1,
                    "lit", v_str("schedule"))),
                "select", cmap(1,
                  "$action", v_str("schedule")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("message"),
                  v_str("schedule"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/message/send"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("message")),
                  cmap(1,
                    "lit", v_str("send"))),
                "select", cmap(1,
                  "$action", v_str("send")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("message"),
                  v_str("send"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/messages"),
                "segments", clist(1,
                  cmap(1,
                    "lit", v_str("messages"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(1,
                  v_str("messages"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/messages/failed"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "lit", v_str("failed"))),
                "select", cmap(1,
                  "$action", v_str("failed")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("messages"),
                  v_str("failed"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/messages/inbox"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "lit", v_str("inbox"))),
                "select", cmap(1,
                  "$action", v_str("inbox")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("messages"),
                  v_str("inbox"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("messageid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/messages/{messageid}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "messageid", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("messages"),
                  v_str("{id}"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/messages/schedule"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "lit", v_str("schedule"))),
                "select", cmap(1,
                  "$action", v_str("schedule")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("messages"),
                  v_str("schedule"))))),
          "remove", cmap(3,
            "input", v_str("data"),
            "name", v_str("remove"),
            "points", clist(2,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("messageid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/messages/{messageid}"),
                "rename", cmap(1,
                  "param", cmap(1,
                    "messageid", v_str("id"))),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "var", v_str("id"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("messages"),
                  v_str("{id}"))),
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("messageid"),
                      "orig", v_str("messageid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("DELETE"),
                "orig", v_str("/messages/schedule/{messageid}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("messages")),
                  cmap(1,
                    "lit", v_str("schedule")),
                  cmap(1,
                    "var", v_str("messageid"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("messageid"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("messages"),
                  v_str("schedule"),
                  v_str("{messageid}")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("schedule"))))),
      "one_time_password", cmap(4,
        "fields", clist(7,
          cmap(3,
            "name", v_str("destination"),
            "short", v_str("The phone number of the recipient."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("length"),
            "short", v_str("The length of the generated passcode."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("metadata"),
            "short", v_str("A JSON object of no longer than 1024 bytes, containing as many parameters as you wish, to store data for use in your application."),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("passcode"),
            "short", v_str("A passcode you supply for use in the message template."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("sender"),
            "short", v_str("The sender of the message."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("template"),
            "short", v_str("A template to use as the content for the message."),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("validity"),
            "short", v_str("The length of time in seconds for which the generated passcode should be valid."),
            "type", v_str("`$NUMBER`"))),
        "name", v_str("one_time_password"),
        "op", cmap(2,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(2,
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/otp/send"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("otp")),
                  cmap(1,
                    "lit", v_str("send"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("otp"),
                  v_str("send"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("POST"),
                "orig", v_str("/otp/verify"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("otp")),
                  cmap(1,
                    "lit", v_str("verify"))),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("otp"),
                  v_str("verify"))))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("messageid"),
                      "orig", v_str("messageid"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/otp/{messageid}"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("otp")),
                  cmap(1,
                    "var", v_str("messageid"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("messageid"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("otp"),
                  v_str("{messageid}")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("otp"))))),
      "schedule", cmap(4,
        "fields", v_list(),
        "name", v_str("schedule"),
        "op", v_map(),
        "relations", cmap(1,
          "ancestors", v_list())),
      "swagger", cmap(4,
        "fields", v_list(),
        "name", v_str("swagger"),
        "op", v_map(),
        "relations", cmap(1,
          "ancestors", v_list())),
      "util", cmap(4,
        "fields", v_list(),
        "name", v_str("util"),
        "op", cmap(1,
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(2,
              cmap(8,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("errorcode"),
                      "orig", v_str("errorcode"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/utils/errors/{errorcode}"),
                "segments", clist(3,
                  cmap(1,
                    "lit", v_str("utils")),
                  cmap(1,
                    "lit", v_str("errors")),
                  cmap(1,
                    "var", v_str("errorcode"))),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("errorcode"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(3,
                  v_str("utils"),
                  v_str("errors"),
                  v_str("{errorcode}"))),
              cmap(8,
                "args", v_map(),
                "kind", v_str("http"),
                "method", v_str("GET"),
                "orig", v_str("/utils/test"),
                "segments", clist(2,
                  cmap(1,
                    "lit", v_str("utils")),
                  cmap(1,
                    "lit", v_str("test"))),
                "select", cmap(1,
                  "$action", v_str("test")),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body`")),
                "parts", clist(2,
                  v_str("utils"),
                  v_str("test")))))),
        "relations", cmap(1,
          "ancestors", clist(1,
            clist(1,
              v_str("error")))))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
