# thesmsworks data — generated entity accessors.
#
# GENERATED by @voxgig/sdkgen (py-data target). Edits are overwritten.
#
# One accessor per entity. Column names and dtypes come from the API model,
# so `ad.<tab>` and `ad.thing?` replace a trip to the reference docs.

from __future__ import annotations

import pandas as pd

from .fetch import drain, MAX_PAGES_DEFAULT
from .frames import build_frame, to_series, FLATTEN_DEFAULT


class EntityFrames:
    """Mixin carrying the generated accessors. Mixed into <Name>Data."""

    _ACCESSORS = [
        "batch",
        "message_message",
        "message_schedule",
    ]

    def batch(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One batch record, by id, as a Series.

        Columns:
          id (string)
        """
        rec = self.sdk.Batch().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "id": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def message_message(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One message_message record, by id, as a Series.

        Columns:
          credits (Float64)
          destination (string)
          from (string)
          id (string)
          keyword (string)
          limit (Float64)
          metadata (object)
          sender (string)
          skip (Float64)
          status (string)
          to (string)
          unread (boolean)
        """
        rec = self.sdk.MessageMessage().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "credits": "Float64",
                "destination": "string",
                "from": "string",
                "id": "string",
                "keyword": "string",
                "limit": "Float64",
                "metadata": "object",
                "sender": "string",
                "skip": "Float64",
                "status": "string",
                "to": "string",
                "unread": "boolean",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def message_schedule(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One message_schedule record, by id, as a Series.

        Columns:
          id (string)
        """
        rec = self.sdk.MessageSchedule().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "id": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )
