package voxgig.thesmsworkssdk.core

import voxgig.thesmsworkssdk.utility.Json

/** Static SDK configuration and by-name feature construction. */
@Suppress("UNCHECKED_CAST")
object Config {

  fun makeConfig(): MutableMap<String, Any?> {
    return Json.parse(configJson()) as MutableMap<String, Any?>
  }

  // SHARED CONFIG (sdkgen rung L2).
  //
  // The SDK reads the config on every request and never writes to it, so one
  // instance is shared by every client rather than rebuilt per client - the
  // difference between parsing the embedded JSON once and once per client.
  //
  // 'by lazy' defaults to LazyThreadSafetyMode.SYNCHRONIZED, so concurrent
  // first calls build it exactly once.
  //
  // The returned map is SHARED: treat it as read-only. Callers that need to
  // mutate should use makeConfig, which always parses a fresh copy.
  private val sharedConfigVal: MutableMap<String, Any?> by lazy { makeConfig() }

  fun sharedConfig(): MutableMap<String, Any?> = sharedConfigVal

  fun makeFeature(name: String): Feature {
    return when (name) {
      "test" -> voxgig.thesmsworkssdk.feature.TestFeature()
      else -> voxgig.thesmsworkssdk.feature.BaseFeature()
    }
  }

  private fun configJson(): String {
    val b = StringBuilder()
    b.append("{")
    b.append(" \"main\": {")
    b.append("  \"name\": \"Thesmsworks\",")
    b.append("  \"slug\": \"thesmsworks\",")
    b.append("  \"version\": \"0.1.1\",")
    b.append("  \"target\": \"kotlin\"")
    b.append(" },")
    b.append(" \"feature\": {")
    b.append("  \"test\": {")
    b.append("   \"options\": {")
    b.append("    \"active\": false")
    b.append("   }")
    b.append("  }")
    b.append(" },")
    b.append(" \"options\": {")
    b.append("  \"base\": \"https://api.thesmsworks.co.uk/v1\",")
    b.append("  \"auth\": {")
    b.append("   \"prefix\": \"\"")
    b.append("  },")
    b.append("  \"headers\": {")
    b.append("   \"content-type\": \"application/json\"")
    b.append("  },")
    b.append("  \"entity\": {")
    b.append("   \"batch\": {},")
    b.append("   \"batch_message\": {},")
    b.append("   \"credit\": {},")
    b.append("   \"flash\": {},")
    b.append("   \"message\": {},")
    b.append("   \"one_time_password\": {},")
    b.append("   \"schedule\": {},")
    b.append("   \"swagger\": {},")
    b.append("   \"util\": {}")
    b.append("  }")
    b.append(" },")
    b.append(" \"entity\": {")
    b.append("  \"batch\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"batch\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"batchid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/batch/{batchid}\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"batchid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"batch_message\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"ai\",")
    b.append("     \"short\": \"Used to determine whether The SMS Works AI Optimiser should be used in the event that the message is just longer than the 1 or 2 credit boundary.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"content\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Message to send to the recipient\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"deliveryreporturl\",")
    b.append("     \"short\": \"The url to which we should POST delivery reports to for this message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"destinations\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Telephone numbers of each of the recipients\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"schedule\",")
    b.append("     \"short\": \"Date-time at which to send the batch.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sender\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The sender of the message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"tag\",")
    b.append("     \"short\": \"An identifying label for the message, which you can use to filter and report on messages you've sent later.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ttl\",")
    b.append("     \"short\": \"The number of minutes before the delivery report is deleted.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"validity\",")
    b.append("     \"short\": \"The optional number of minutes to attempt delivery before the message is marked as EXPIRED.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"batch_message\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/any\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"any\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/batch/send\",")
    b.append("       \"parts\": [")
    b.append("        \"batch\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"batchid\",")
    b.append("          \"orig\": \"batchid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/batches/schedule/{batchid}\",")
    b.append("       \"parts\": [")
    b.append("        \"batches\",")
    b.append("        \"schedule\",")
    b.append("        \"{batchid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"batchid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"schedule\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"credit\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"credit\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/credits/balance\",")
    b.append("       \"parts\": [")
    b.append("        \"credits\",")
    b.append("        \"balance\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"balance\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"flash\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"flash\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"message\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"ai\",")
    b.append("     \"short\": \"Used to determine whether The SMS Works AI Optimiser should be used in the event that the message is just longer than the 1 or 2 credit boundary.\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"content\",")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Message to send to the recipient.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"credits\",")
    b.append("     \"short\": \"The number of credits used on the message.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"deliveryreporturl\",")
    b.append("     \"short\": \"The url to which we should POST delivery reports to for this message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"destination\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"Telephone number of the recipient\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"from\",")
    b.append("     \"short\": \"The date-time from which you would like matching messages\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"keyword\",")
    b.append("     \"short\": \"The keyword used in the inbound message\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"limit\",")
    b.append("     \"short\": \"The maximum number of messages that you would like returned in this call.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"metadata\",")
    b.append("     \"short\": \"An array of objects containing metadata key/value pairs that have been saved on messages.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"responseemail\",")
    b.append("     \"short\": \"An optional list of email addresses to forward responses to this specific message to.\",")
    b.append("     \"type\": \"`\$ARRAY`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"schedule\",")
    b.append("     \"short\": \"Date at which to send the message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sender\",")
    b.append("     \"op\": {")
    b.append("      \"create\": {")
    b.append("       \"type\": \"`\$STRING`\"")
    b.append("      }")
    b.append("     },")
    b.append("     \"req\": true,")
    b.append("     \"short\": \"The sender of the message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"skip\",")
    b.append("     \"short\": \"The number of results you would like to ignore before returning messages.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"status\",")
    b.append("     \"short\": \"The status of the messages you would like returned (either 'SENT', 'DELIVERED', 'EXPIRED', 'UNDELIVERABLE', 'REJECTED' or 'INCOMING')\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"tag\",")
    b.append("     \"short\": \"An identifying label for the message, which you can use to filter and report on messages you've sent later.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"to\",")
    b.append("     \"short\": \"The date-time to which you would like matching messages\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"ttl\",")
    b.append("     \"short\": \"The optional number of minutes before the delivery report is deleted.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"unread\",")
    b.append("     \"short\": \"In queries for incoming messages ('status' is 'INCOMING'), specify whether you explicitly want unread messages (true) or read messages (false).\",")
    b.append("     \"type\": \"`\$BOOLEAN`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"validity\",")
    b.append("     \"short\": \"The optional number of minutes to attempt delivery before the message is marked as EXPIRED.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"message\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/flash\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"flash\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"flash\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"schedule\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/message/send\",")
    b.append("       \"parts\": [")
    b.append("        \"message\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"send\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages/failed\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"failed\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"failed\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/messages/inbox\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"inbox\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"inbox\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/messages/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"messageid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/messages/schedule\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"schedule\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"schedule\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"remove\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"remove\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"id\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/messages/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"{id}\"")
    b.append("       ],")
    b.append("       \"rename\": {")
    b.append("        \"param\": {")
    b.append("         \"messageid\": \"id\"")
    b.append("        }")
    b.append("       },")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"id\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"messageid\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"DELETE\",")
    b.append("       \"orig\": \"/messages/schedule/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"messages\",")
    b.append("        \"schedule\",")
    b.append("        \"{messageid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"messageid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"schedule\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"one_time_password\": {")
    b.append("   \"fields\": [")
    b.append("    {")
    b.append("     \"name\": \"destination\",")
    b.append("     \"short\": \"The phone number of the recipient.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"length\",")
    b.append("     \"short\": \"The length of the generated passcode.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"metadata\",")
    b.append("     \"short\": \"A JSON object of no longer than 1024 bytes, containing as many parameters as you wish, to store data for use in your application.\",")
    b.append("     \"type\": \"`\$OBJECT`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"passcode\",")
    b.append("     \"short\": \"A passcode you supply for use in the message template.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"sender\",")
    b.append("     \"short\": \"The sender of the message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"template\",")
    b.append("     \"short\": \"A template to use as the content for the message.\",")
    b.append("     \"type\": \"`\$STRING`\"")
    b.append("    },")
    b.append("    {")
    b.append("     \"name\": \"validity\",")
    b.append("     \"short\": \"The length of time in seconds for which the generated passcode should be valid.\",")
    b.append("     \"type\": \"`\$NUMBER`\"")
    b.append("    }")
    b.append("   ],")
    b.append("   \"name\": \"one_time_password\",")
    b.append("   \"op\": {")
    b.append("    \"create\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"create\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/otp/send\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"send\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"POST\",")
    b.append("       \"orig\": \"/otp/verify\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"verify\"")
    b.append("       ],")
    b.append("       \"select\": {},")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    },")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"messageid\",")
    b.append("          \"orig\": \"messageid\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/otp/{messageid}\",")
    b.append("       \"parts\": [")
    b.append("        \"otp\",")
    b.append("        \"{messageid}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"messageid\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"otp\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  },")
    b.append("  \"schedule\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"schedule\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"swagger\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"swagger\",")
    b.append("   \"op\": {},")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": []")
    b.append("   }")
    b.append("  },")
    b.append("  \"util\": {")
    b.append("   \"fields\": [],")
    b.append("   \"name\": \"util\",")
    b.append("   \"op\": {")
    b.append("    \"load\": {")
    b.append("     \"input\": \"data\",")
    b.append("     \"name\": \"load\",")
    b.append("     \"points\": [")
    b.append("      {")
    b.append("       \"args\": {")
    b.append("        \"params\": [")
    b.append("         {")
    b.append("          \"kind\": \"param\",")
    b.append("          \"name\": \"errorcode\",")
    b.append("          \"orig\": \"errorcode\",")
    b.append("          \"reqd\": true,")
    b.append("          \"type\": \"`\$STRING`\"")
    b.append("         }")
    b.append("        ]")
    b.append("       },")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/utils/errors/{errorcode}\",")
    b.append("       \"parts\": [")
    b.append("        \"utils\",")
    b.append("        \"errors\",")
    b.append("        \"{errorcode}\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"exist\": [")
    b.append("         \"errorcode\"")
    b.append("        ]")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      },")
    b.append("      {")
    b.append("       \"args\": {},")
    b.append("       \"kind\": \"http\",")
    b.append("       \"method\": \"GET\",")
    b.append("       \"orig\": \"/utils/test\",")
    b.append("       \"parts\": [")
    b.append("        \"utils\",")
    b.append("        \"test\"")
    b.append("       ],")
    b.append("       \"select\": {")
    b.append("        \"\$action\": \"test\"")
    b.append("       },")
    b.append("       \"transform\": {")
    b.append("        \"req\": \"`reqdata`\",")
    b.append("        \"res\": \"`body`\"")
    b.append("       }")
    b.append("      }")
    b.append("     ]")
    b.append("    }")
    b.append("   },")
    b.append("   \"relations\": {")
    b.append("    \"ancestors\": [")
    b.append("     [")
    b.append("      \"error\"")
    b.append("     ]")
    b.append("    ]")
    b.append("   }")
    b.append("  }")
    b.append(" }")
    b.append("}")
    return b.toString()
  }
}
