(* Thesmsworks SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* Batch entity bound to a client:  batch client entopts *)
let batch (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_batch.make client entopts

(* BatchMessage entity bound to a client:  batch_message client entopts *)
let batch_message (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_batch_message.make client entopts

(* Credit entity bound to a client:  credit client entopts *)
let credit (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_credit.make client entopts

(* Flash entity bound to a client:  flash client entopts *)
let flash (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_flash.make client entopts

(* Message entity bound to a client:  message client entopts *)
let message (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_message.make client entopts

(* OneTimePassword entity bound to a client:  one_time_password client entopts *)
let one_time_password (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_one_time_password.make client entopts

(* Schedule entity bound to a client:  schedule client entopts *)
let schedule (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_schedule.make client entopts

(* Swagger entity bound to a client:  swagger client entopts *)
let swagger (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_swagger.make client entopts

(* Util entity bound to a client:  util client entopts *)
let util (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_util.make client entopts
