(* Thesmsworks SDK utility: prepare_auth.
 *
 * GENERATED by @voxgig/sdkgen (src/cmp/ocaml/PrepareAuth_ocaml.ts), not
 * copied from tm/ocaml - WHERE the credential goes and UNDER WHAT NAME is a
 * fact about this API, and a template can hold only one answer. This SDK's
 * scheme places it in the `authorization` header.
 *
 * Sdk_runtime binds `prepare_auth_util` to this one and registers it in the
 * utility record, so every caller reaches it exactly as before. *)

open Voxgig_struct
open Sdk_types
open Sdk_helpers

(* THE PLACEMENT THIS SDK WAS GENERATED FOR, DECLARED rather than left
 * implicit in the code below.
 *
 *   cred_active  false only for main.kit.config.auth.active: false
 *   cred_where   header | query | cookie
 *   cred_name    the key used - ALREADY LOWER-CASED for a header, because
 *                every header key the runtime writes is; verbatim for a
 *                query parameter or a cookie, which are case-sensitive
 *
 * They exist so the SHIPPED suite can hold the runtime to its own contract
 * instead of guessing at it: test/t_pipeline.ml's four `prepare_auth.*`
 * cases hardcoded `spec.headers["authorization"]`, so they failed on any
 * SDK whose scheme is not a header - precisely the SDK this change exists to
 * make work. Reading them is not circular: the assertions still drive the
 * real prepare_auth and check the bag, key and value it actually wrote. *)
let cred_active = true
let cred_where = "header"
let cred_name = "authorization"

let option_apikey = "apikey"
let not_found = "__NOTFOUND__"

(* The client's auth.name option, when set, replaces the name the API declares. *)
let auth_name (options : value) : string =
  match getpath_s options "auth.name" with
  | Str s when s <> "" -> String.lowercase_ascii s
  | _ -> cred_name

let prepare_auth_util (ctx : ctx) : (spec option * sdk_error option) =
  match ctx.c_spec with
  | None -> (None, Some (ctx_make_error ctx "auth_no_spec" "Expected context spec property to be defined."))
  | Some spec ->
    let headers = spec.sp_headers in
    let options = client_options_map (cc ctx) in
    (match getp options "auth" with
     (* `auth: null` is the documented suppression, and a public API that
      * needs no auth omits the block entirely. Both land here. *)
     | Noval | Null -> ignore (delprop headers (Str cred_name)); (Some spec, None)
     | _ ->
       let name = auth_name options in
       (* A credential left under the declared name would travel beside the renamed one. *)
       if name <> cred_name then ignore (delprop headers (Str cred_name));
       let apikey = getprop ~alt:(Str not_found) options (Str option_apikey) in
       let is_notfound = (match apikey with Str s -> s = not_found | _ -> false) in
       let no_apikey = is_notfound || is_noval apikey || apikey = Str "" in
       if no_apikey then
         ignore (delprop headers (Str name))
       else begin
         let auth_prefix = match getpath_s options "auth.prefix" with Str s -> s | _ -> "" in
         let apikey_val = match apikey with Str s -> s | _ -> "" in
         (* Empty prefix (a raw apiKey credential) must not add a leading space. *)
         let authval = if auth_prefix <> "" then auth_prefix ^ " " ^ apikey_val else apikey_val in
         setp headers name (Str authval)
       end;
       (Some spec, None))
