-- Thesmsworks SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
  , batch
  , batch_message
  , credit
  , flash
  , message
  , one_time_password
  , schedule
  , swagger
  , util
  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

-- | The Batch entity bound to this client.
batch :: Client -> Value -> IO Entity
batch client entopts = F.makeEntity client "batch" entopts

-- | The BatchMessage entity bound to this client.
batch_message :: Client -> Value -> IO Entity
batch_message client entopts = F.makeEntity client "batch_message" entopts

-- | The Credit entity bound to this client.
credit :: Client -> Value -> IO Entity
credit client entopts = F.makeEntity client "credit" entopts

-- | The Flash entity bound to this client.
flash :: Client -> Value -> IO Entity
flash client entopts = F.makeEntity client "flash" entopts

-- | The Message entity bound to this client.
message :: Client -> Value -> IO Entity
message client entopts = F.makeEntity client "message" entopts

-- | The OneTimePassword entity bound to this client.
one_time_password :: Client -> Value -> IO Entity
one_time_password client entopts = F.makeEntity client "one_time_password" entopts

-- | The Schedule entity bound to this client.
schedule :: Client -> Value -> IO Entity
schedule client entopts = F.makeEntity client "schedule" entopts

-- | The Swagger entity bound to this client.
swagger :: Client -> Value -> IO Entity
swagger client entopts = F.makeEntity client "swagger" entopts

-- | The Util entity bound to this client.
util :: Client -> Value -> IO Entity
util client entopts = F.makeEntity client "util" entopts

