-- Thesmsworks SDK test runner (generated by @voxgig/sdkgen).
--
-- OFFLINE lane (always): a test-mode client seeded from the generated entity
-- test data answers operations from an in-memory store — no server needed.
-- LIVE lane (only when SDK_TEST_BASE is set): the same flow over real HTTP.

import VoxgigStruct
import SdkJson
import SdkRuntime
import SdkClient

open VoxgigStruct

initialize npass : IO.Ref Nat ← IO.mkRef 0
initialize nfail : IO.Ref Nat ← IO.mkRef 0

def pass (msg : String) : SIO Unit := do
  npass.modify (· + 1)
  IO.println s!"ok   - {msg}"

def fail (msg : String) : SIO Unit := do
  nfail.modify (· + 1)
  IO.println s!"FAIL - {msg}"

def defaultBase : String := "http://localhost:8901"

def main : IO UInt32 := do
  let liveBase ← IO.getEnv "SDK_TEST_BASE"
  let ctx ← mkCtx
  let offline : SIO Unit := do
    -- batch: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/batch/BatchTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - batch: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "batch"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Batch.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"batch.load offline (id={wid})"
          else fail s!"batch.load offline: got {gid}, want {wid}"
)
    -- message: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/message/MessageTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - message: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "message"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Message.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"message.load offline (id={wid})"
          else fail s!"message.load offline: got {gid}, want {wid}"
        -- create -> load back -> remove, all in the store
        let newmap ← SdkRuntime.gp (← SdkRuntime.gp seed "new") "message"
        let nks ← keysof newmap
        if nks.size > 0 then do
          let payload ← SdkRuntime.gp newmap nks[0]!
          let created ← Message.create tclient payload (← emptyMap)
          let cid ← SdkRuntime.gpS created "id"
          if cid == "" then fail "message.create offline returned no id" else do
            let m2 ← newMap #[("id", Value.str cid)]
            let back ← Message.load tclient m2 (← emptyMap)
            if (← SdkRuntime.gpS back "id") == cid then
              pass s!"message.create/load offline (id={cid})"
            else fail s!"message.create/load offline mismatch"
            let _ ← Message.remove tclient m2 (← emptyMap)
            let gone ← Message.load tclient m2 (← emptyMap)
            match gone with
            | Value.map _ => fail s!"message.remove offline: still present"
            | _ => pass s!"message.remove offline (id={cid})"
)
    -- one_time_password: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/one_time_password/OneTimePasswordTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - one_time_password: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "one_time_password"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← One_time_password.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"one_time_password.load offline (id={wid})"
          else fail s!"one_time_password.load offline: got {gid}, want {wid}"
)
    -- util: offline (test-mode) entity behaviour
    (do
      let seedPath := "../.sdk/test/entity/util/UtilTestData.json"
      if !(← System.FilePath.pathExists seedPath) then
        IO.println s!"skip - util: no seed at {seedPath}"
      else do
        let seed ← SdkJson.jsonRead (← IO.FS.readFile seedPath)
        let tclient ← Sdk.testSdk0 seed
        let existing ← SdkRuntime.gp (← SdkRuntime.gp seed "existing") "util"
        let ids ← keysof existing
        -- load the first seeded entity by id
        if ids.size > 0 then do
          let wid := ids[0]!
          let m ← newMap #[("id", Value.str wid)]
          let got ← Util.load tclient m (← emptyMap)
          let gid ← SdkRuntime.gpS got "id"
          if gid == wid then pass s!"util.load offline (id={wid})"
          else fail s!"util.load offline: got {gid}, want {wid}"
)
  offline.run ctx
  match liveBase with
  | none => IO.println "skip - live lane (set SDK_TEST_BASE to enable)"
  | some base => do
    let live : SIO Unit := do
      let opts ← newMap #[("base", .str base)]
      let client ← Sdk.newSdk opts
      -- message: create / load / remove round-trip
      (do
        let d ← SdkJson.jsonRead "{}"
        let created ← Message.create client d (← emptyMap)
        let nid ← SdkRuntime.gpS created "id"
        if nid == "" then fail "message.create returned no id" else do
          let m ← newMap #[("id", .str nid)]
          let back ← Message.load client m (← emptyMap)
          let bid ← SdkRuntime.gpS back "id"
          if bid == nid then pass s!"message.create/load round-trip (id={nid})"
          else fail s!"message.load mismatch: {bid} != {nid}"
          let _ ← Message.remove client m (← emptyMap)
          pass s!"message.remove (id={nid})")
    live.run ctx
  let p ← npass.get
  let f ← nfail.get
  IO.println ""
  IO.println s!"PASS {p}  FAIL {f}"
  if f > 0 then return 1 else return 0
