;; Thesmsworks SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.batch :as e-batch]
            [sdk.entity.batch_message :as e-batch_message]
            [sdk.entity.credit :as e-credit]
            [sdk.entity.flash :as e-flash]
            [sdk.entity.message :as e-message]
            [sdk.entity.one_time_password :as e-one_time_password]
            [sdk.entity.schedule :as e-schedule]
            [sdk.entity.swagger :as e-swagger]
            [sdk.entity.util :as e-util]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def prepare client/prepare)
(def options-map client/options-map)

;; Batch accessor: (batch client data)
(defn batch [client data] (e-batch/make client data))

;; BatchMessage accessor: (batch_message client data)
(defn batch_message [client data] (e-batch_message/make client data))

;; Credit accessor: (credit client data)
(defn credit [client data] (e-credit/make client data))

;; Flash accessor: (flash client data)
(defn flash [client data] (e-flash/make client data))

;; Message accessor: (message client data)
(defn message [client data] (e-message/make client data))

;; OneTimePassword accessor: (one_time_password client data)
(defn one_time_password [client data] (e-one_time_password/make client data))

;; Schedule accessor: (schedule client data)
(defn schedule [client data] (e-schedule/make client data))

;; Swagger accessor: (swagger client data)
(defn swagger [client data] (e-swagger/make client data))

;; Util accessor: (util client data)
(defn util [client data] (e-util/make client data))
