;; Thesmsworks SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "batch" (vs/jm
        "fields" (vs/jt)
        "name" "batch"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "batchid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/batch/{batchid}"
                "parts" (vs/jt
                  "batch"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "batchid" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "batch_message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "ai"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "content"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "deliveryreporturl"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "destination"
            "req" true
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "schedule"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "sender"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "tag"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "ttl"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "validity"
            "req" false
            "type" "`$NUMBER`"))
        "name" "batch_message"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/batch/any"
                "parts" (vs/jt
                  "batch"
                  "any")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/batch/schedule"
                "parts" (vs/jt
                  "batch"
                  "schedule")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 2
                "method" "POST"
                "orig" "/batch/send"
                "parts" (vs/jt
                  "batch"
                  "send")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "batchid"
                      "orig" "batchid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/batches/schedule/{batchid}"
                "parts" (vs/jt
                  "batches"
                  "schedule"
                  "{batchid}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "batchid"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "schedule"))))
      "credit" (vs/jm
        "fields" (vs/jt)
        "name" "credit"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "GET"
                "orig" "/credits/balance"
                "parts" (vs/jt
                  "credits"
                  "balance")
                "select" (vs/jm
                  "$action" "balance")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "flash" (vs/jm
        "fields" (vs/jt)
        "name" "flash"
        "op" (vs/jm)
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "ai"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "content"
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "credit"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "deliveryreporturl"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "destination"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "from"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "keyword"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 7
            "name" "limit"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 8
            "name" "metadata"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 9
            "name" "responseemail"
            "req" false
            "type" "`$ARRAY`")
          (vs/jm
            "active" true
            "index$" 10
            "name" "schedule"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 11
            "name" "sender"
            "op" (vs/jm
              "create" (vs/jm
                "req" false
                "type" "`$STRING`"))
            "req" true
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 12
            "name" "skip"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 13
            "name" "status"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 14
            "name" "tag"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 15
            "name" "to"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 16
            "name" "ttl"
            "req" false
            "type" "`$NUMBER`")
          (vs/jm
            "active" true
            "index$" 17
            "name" "unread"
            "req" false
            "type" "`$BOOLEAN`")
          (vs/jm
            "active" true
            "index$" 18
            "name" "validity"
            "req" false
            "type" "`$NUMBER`"))
        "name" "message"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/message/flash"
                "parts" (vs/jt
                  "message"
                  "flash")
                "select" (vs/jm
                  "$action" "flash")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/message/schedule"
                "parts" (vs/jt
                  "message"
                  "schedule")
                "select" (vs/jm
                  "$action" "schedule")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 2
                "method" "POST"
                "orig" "/message/send"
                "parts" (vs/jt
                  "message"
                  "send")
                "select" (vs/jm
                  "$action" "send")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 3
                "method" "POST"
                "orig" "/messages"
                "parts" (vs/jt
                  "messages")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 4
                "method" "POST"
                "orig" "/messages/failed"
                "parts" (vs/jt
                  "messages"
                  "failed")
                "select" (vs/jm
                  "$action" "failed")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 5
                "method" "POST"
                "orig" "/messages/inbox"
                "parts" (vs/jt
                  "messages"
                  "inbox")
                "select" (vs/jm
                  "$action" "inbox")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/messages/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "messageid" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "GET"
                "orig" "/messages/schedule"
                "parts" (vs/jt
                  "messages"
                  "schedule")
                "select" (vs/jm
                  "$action" "schedule")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "key$" "remove"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "id"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "DELETE"
                "orig" "/messages/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "messageid" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "messageid"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 1
                "method" "DELETE"
                "orig" "/messages/schedule/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "schedule"
                  "{messageid}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "messageid"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "schedule"))))
      "one_time_password" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "active" true
            "index$" 0
            "name" "destination"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 1
            "name" "length"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 2
            "name" "metadata"
            "req" false
            "type" "`$OBJECT`")
          (vs/jm
            "active" true
            "index$" 3
            "name" "passcode"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 4
            "name" "sender"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 5
            "name" "template"
            "req" false
            "type" "`$STRING`")
          (vs/jm
            "active" true
            "index$" 6
            "name" "validity"
            "req" false
            "type" "`$NUMBER`"))
        "name" "one_time_password"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "key$" "create"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 0
                "method" "POST"
                "orig" "/otp/send"
                "parts" (vs/jt
                  "otp"
                  "send")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "POST"
                "orig" "/otp/verify"
                "parts" (vs/jt
                  "otp"
                  "verify")
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "messageid"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/otp/{messageid}"
                "parts" (vs/jt
                  "otp"
                  "{messageid}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "messageid"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "otp"))))
      "schedule" (vs/jm
        "fields" (vs/jt)
        "name" "schedule"
        "op" (vs/jm)
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "swagger" (vs/jm
        "fields" (vs/jt)
        "name" "swagger"
        "op" (vs/jm)
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "util" (vs/jm
        "fields" (vs/jt)
        "name" "util"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "key$" "load"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "active" true
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "active" true
                      "index$" 0
                      "kind" "param"
                      "name" "errorcode"
                      "orig" "errorcode"
                      "reqd" true
                      "type" "`$STRING`")))
                "index$" 0
                "method" "GET"
                "orig" "/utils/errors/{errorcode}"
                "parts" (vs/jt
                  "utils"
                  "errors"
                  "{errorcode}")
                "select" (vs/jm
                  "exist" (vs/jt
                    "errorcode"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "active" true
                "args" (vs/jm)
                "index$" 1
                "method" "GET"
                "orig" "/utils/test"
                "parts" (vs/jt
                  "utils"
                  "test")
                "select" (vs/jm
                  "$action" "test")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt
            (vs/jt
              "error")))))
    "feature" (vs/jm
      "test" (vs/jm
        "options" (vs/jm
          "active" false)))
    "main" (vs/jm
      "name" "Thesmsworks")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "")
      "base" "https://api.thesmsworks.co.uk/v1"
      "entity" (vs/jm
        "batch" (vs/jm)
        "batch_message" (vs/jm)
        "credit" (vs/jm)
        "flash" (vs/jm)
        "message" (vs/jm)
        "one_time_password" (vs/jm)
        "schedule" (vs/jm)
        "swagger" (vs/jm)
        "util" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))
