;; Thesmsworks SDK configuration (generated by @voxgig/sdkgen).
(ns sdk.config
  (:require [voxgig.struct :as vs]
            [sdk.feature.secrets :as fx-secrets]))

(defn make-config []
  (vs/jm
    "entity" (vs/jm
      "batch" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "title" "Id"
            "type" "`$STRING`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "batch"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "batchid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/batch/{batchid}"
                "parts" (vs/jt
                  "batch"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "batchid" "id"))
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "batch")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "batch_message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "ai"
            "short" "Used to determine whether The SMS Works AI Optimiser should be used in the event that the message is just longer than the 1 or 2 credit boundary."
            "title" "Ai"
            "type" "`$BOOLEAN`")
          (vs/jm
            "name" "content"
            "req" true
            "short" "Message to send to the recipient"
            "title" "Content"
            "type" "`$STRING`")
          (vs/jm
            "name" "deliveryreporturl"
            "short" "The url to which we should POST delivery reports to for this message."
            "title" "Deliveryreporturl"
            "type" "`$STRING`")
          (vs/jm
            "name" "destinations"
            "req" true
            "short" "Telephone numbers of each of the recipients"
            "title" "Destinations"
            "type" "`$ARRAY`")
          (vs/jm
            "name" "schedule"
            "short" "Date-time at which to send the batch."
            "title" "Schedule"
            "type" "`$STRING`")
          (vs/jm
            "name" "sender"
            "req" true
            "short" "The sender of the message."
            "title" "Sender"
            "type" "`$STRING`")
          (vs/jm
            "name" "tag"
            "short" "An identifying label for the message, which you can use to filter and report on messages you've sent later."
            "title" "Tag"
            "type" "`$STRING`")
          (vs/jm
            "name" "ttl"
            "short" "The number of minutes before the delivery report is deleted."
            "title" "Ttl"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "validity"
            "short" "The optional number of minutes to attempt delivery before the message is marked as EXPIRED."
            "title" "Validity"
            "type" "`$NUMBER`"))
        "name" "batch_message"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/batch/any"
                "parts" (vs/jt
                  "batch"
                  "any")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "batch")
                  (vs/jm
                    "lit" "any"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/batch/schedule"
                "parts" (vs/jt
                  "batch"
                  "schedule")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "batch")
                  (vs/jm
                    "lit" "schedule"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/batch/send"
                "parts" (vs/jt
                  "batch"
                  "send")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "batch")
                  (vs/jm
                    "lit" "send"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "credit" (vs/jm
        "fields" (vs/jt)
        "name" "credit"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/credits/balance"
                "parts" (vs/jt
                  "credits"
                  "balance")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "credits")
                  (vs/jm
                    "lit" "balance"))
                "select" (vs/jm
                  "$action" "balance")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "message" (vs/jm
        "fields" (vs/jt)
        "name" "message"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/messages/failed"
                "parts" (vs/jt
                  "messages"
                  "failed")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "lit" "failed"))
                "select" (vs/jm
                  "$action" "failed")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/message/flash"
                "parts" (vs/jt
                  "message"
                  "flash")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "message")
                  (vs/jm
                    "lit" "flash"))
                "select" (vs/jm
                  "$action" "flash")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/messages/inbox"
                "parts" (vs/jt
                  "messages"
                  "inbox")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "lit" "inbox"))
                "select" (vs/jm
                  "$action" "inbox")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/message/schedule"
                "parts" (vs/jt
                  "message"
                  "schedule")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "message")
                  (vs/jm
                    "lit" "schedule"))
                "select" (vs/jm
                  "$action" "schedule")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/message/send"
                "parts" (vs/jt
                  "message"
                  "send")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "message")
                  (vs/jm
                    "lit" "send"))
                "select" (vs/jm
                  "$action" "send")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "message_message" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "credits"
            "short" "The number of credits used on the message."
            "title" "Credits"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "destination"
            "short" "The phone number of the recipient."
            "title" "Destination"
            "type" "`$STRING`")
          (vs/jm
            "name" "from"
            "short" "The date-time from which you would like matching messages"
            "title" "From"
            "type" "`$STRING`")
          (vs/jm
            "name" "id"
            "title" "Id"
            "type" "`$STRING`")
          (vs/jm
            "name" "keyword"
            "short" "The keyword used in the inbound message"
            "title" "Keyword"
            "type" "`$STRING`")
          (vs/jm
            "name" "limit"
            "short" "The maximum number of messages that you would like returned in this call."
            "title" "Limit"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "metadata"
            "short" "An array of objects containing metadata key/value pairs that have been saved on messages."
            "title" "Metadata"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "sender"
            "short" "The sender of the message (this can be the configured sender name for an outbound message or the senders phone number for an inbound message)."
            "title" "Sender"
            "type" "`$STRING`")
          (vs/jm
            "name" "skip"
            "short" "The number of results you would like to ignore before returning messages."
            "title" "Skip"
            "type" "`$NUMBER`")
          (vs/jm
            "name" "status"
            "short" "The status of the messages you would like returned (either 'SENT', 'DELIVERED', 'EXPIRED', 'UNDELIVERABLE', 'REJECTED' or 'INCOMING')"
            "title" "Status"
            "type" "`$STRING`")
          (vs/jm
            "name" "to"
            "short" "The date-time to which you would like matching messages"
            "title" "To"
            "type" "`$STRING`")
          (vs/jm
            "name" "unread"
            "short" "In queries for incoming messages ('status' is 'INCOMING'), specify whether you explicitly want unread messages (true) or read messages (false)."
            "title" "Unread"
            "type" "`$BOOLEAN`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "message_message"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/messages"
                "parts" (vs/jt
                  "messages")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/messages/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "messageid" "id"))
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/messages/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "messageid" "id"))
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "message_schedule" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "title" "Id"
            "type" "`$STRING`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "message_schedule"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/messages/schedule"
                "parts" (vs/jt
                  "messages"
                  "schedule")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "lit" "schedule"))
                "select" (vs/jm
                  "$action" "schedule")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/messages/schedule/{messageid}"
                "parts" (vs/jt
                  "messages"
                  "schedule"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "messageid" "id"))
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "messages")
                  (vs/jm
                    "lit" "schedule")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "one_time_password" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "destination"
            "short" "The phone number of the recipient."
            "title" "Destination"
            "type" "`$STRING`")
          (vs/jm
            "name" "length"
            "short" "The length of the generated passcode."
            "title" "Length"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "metadata"
            "short" "A JSON object of no longer than 1024 bytes, containing as many parameters as you wish, to store data for use in your application."
            "title" "Metadata"
            "type" "`$OBJECT`")
          (vs/jm
            "name" "passcode"
            "short" "A passcode you supply for use in the message template."
            "title" "Passcode"
            "type" "`$STRING`")
          (vs/jm
            "name" "sender"
            "short" "The sender of the message."
            "title" "Sender"
            "type" "`$STRING`")
          (vs/jm
            "name" "template"
            "short" "A template to use as the content for the message."
            "title" "Template"
            "type" "`$STRING`")
          (vs/jm
            "name" "validity"
            "short" "The length of time in seconds for which the generated passcode should be valid."
            "title" "Validity"
            "type" "`$NUMBER`"))
        "name" "one_time_password"
        "op" (vs/jm
          "create" (vs/jm
            "input" "data"
            "name" "create"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/otp/send"
                "parts" (vs/jt
                  "otp"
                  "send")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "otp")
                  (vs/jm
                    "lit" "send"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "POST"
                "orig" "/otp/verify"
                "parts" (vs/jt
                  "otp"
                  "verify")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "otp")
                  (vs/jm
                    "lit" "verify"))
                "select" (vs/jm)
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))))
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "messageid"
                      "orig" "messageid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/otp/{messageid}"
                "parts" (vs/jt
                  "otp"
                  "{messageid}")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "otp")
                  (vs/jm
                    "var" "messageid"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "messageid"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "schedule" (vs/jm
        "fields" (vs/jt
          (vs/jm
            "name" "id"
            "title" "Id"
            "type" "`$STRING`"))
        "id" (vs/jm
          "field" "id"
          "name" "id")
        "name" "schedule"
        "op" (vs/jm
          "remove" (vs/jm
            "input" "data"
            "name" "remove"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "id"
                      "orig" "batchid"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "DELETE"
                "orig" "/batches/schedule/{batchid}"
                "parts" (vs/jt
                  "batches"
                  "schedule"
                  "{id}")
                "rename" (vs/jm
                  "param" (vs/jm
                    "batchid" "id"))
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "batches")
                  (vs/jm
                    "lit" "schedule")
                  (vs/jm
                    "var" "id"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "id"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt)))
      "util" (vs/jm
        "fields" (vs/jt)
        "name" "util"
        "op" (vs/jm
          "load" (vs/jm
            "input" "data"
            "name" "load"
            "points" (vs/jt
              (vs/jm
                "args" (vs/jm
                  "params" (vs/jt
                    (vs/jm
                      "kind" "param"
                      "name" "errorcode"
                      "orig" "errorcode"
                      "reqd" true
                      "type" "`$STRING`")))
                "kind" "http"
                "method" "GET"
                "orig" "/utils/errors/{errorcode}"
                "parts" (vs/jt
                  "utils"
                  "errors"
                  "{errorcode}")
                "rename" (vs/jm)
                "segments" (vs/jt
                  (vs/jm
                    "lit" "utils")
                  (vs/jm
                    "lit" "errors")
                  (vs/jm
                    "var" "errorcode"))
                "select" (vs/jm
                  "exist" (vs/jt
                    "errorcode"))
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`"))
              (vs/jm
                "args" (vs/jm)
                "kind" "http"
                "method" "GET"
                "orig" "/utils/test"
                "parts" (vs/jt
                  "utils"
                  "test")
                "rename" (vs/jm)
                "response" (vs/jm
                  "kind" "json"
                  "media" "application/json;charset=UTF-8")
                "segments" (vs/jt
                  (vs/jm
                    "lit" "utils")
                  (vs/jm
                    "lit" "test"))
                "select" (vs/jm
                  "$action" "test")
                "transform" (vs/jm
                  "req" "`reqdata`"
                  "res" "`body`")))))
        "relations" (vs/jm
          "ancestors" (vs/jt))))
    "feature" (vs/jm
      "audit" (vs/jm
        "options" (vs/jm
          "active" false
          "actor" "anonymous"
          "max" 1000)
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "sink" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "cache" (vs/jm
        "options" (vs/jm
          "active" false
          "max" 256
          "methods" (vs/jt
            "GET")
          "ttl" 5000)
        "optspec" (vs/jm
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "clienttrack" (vs/jm
        "options" (vs/jm
          "active" false
          "clientVersion" "0.0.1")
        "optspec" (vs/jm
          "clientName" "`$STRING`"
          "clientVersion" "`$STRING`"
          "headers" "`$MAP`"
          "idgen" "`$FUNCTION`"
          "sessionId" "`$STRING`")
        "strict" false
        "transport" "none")
      "cost" (vs/jm
        "options" (vs/jm
          "active" false
          "budget" 0
          "currency" "USD"
          "header" ""
          "onBudget" "warn"
          "path" ""
          "perUnit" 0
          "rates" (vs/jm)
          "unit" 0)
        "optspec" (vs/jm
          "actor" "`$STRING`"
          "sink" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "debug" (vs/jm
        "options" (vs/jm
          "active" false
          "max" 100
          "redact" (vs/jt
            "authorization"
            "cookie"
            "set-cookie"
            "api-key"
            "apikey"
            "x-api-key"
            "idempotency-key"))
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "onEntry" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "idempotency" (vs/jm
        "options" (vs/jm
          "active" false
          "header" "Idempotency-Key"
          "methods" (vs/jt
            "POST"
            "PUT"
            "PATCH"
            "DELETE")
          "ops" (vs/jt
            "create"
            "update"
            "remove"))
        "optspec" (vs/jm
          "keygen" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "log" (vs/jm
        "options" (vs/jm
          "active" true)
        "optspec" (vs/jm
          "level" "`$STRING`"
          "logger" "`$ANY`")
        "strict" false
        "transport" "none")
      "metrics" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "netsim" (vs/jm
        "options" (vs/jm
          "active" false
          "errorTimes" 0
          "failEvery" 0
          "failRate" 0
          "failStatus" 503
          "failTimes" 0
          "latency" 0
          "offline" false
          "rateLimitTimes" 0
          "retryAfter" 0
          "seed" 1)
        "optspec" (vs/jm
          "latency" (vs/jt
            "`$ONE`"
            "`$NUMBER`"
            "`$MAP`")
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "paging" (vs/jm
        "options" (vs/jm
          "active" false
          "afterVar" "after"
          "cursorParam" "cursor"
          "firstVar" "first"
          "limitParam" "limit"
          "pageParam" "page"
          "startPage" 1)
        "optspec" (vs/jm
          "limit" "`$NUMBER`"
          "ops" "`$LIST`")
        "strict" false
        "transport" "none")
      "proxy" (vs/jm
        "options" (vs/jm
          "active" false
          "fromEnv" false
          "noProxy" (vs/jt)
          "url" "")
        "optspec" (vs/jm
          "agent" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "ratelimit" (vs/jm
        "options" (vs/jm
          "active" false
          "burst" 5
          "rate" 5)
        "optspec" (vs/jm
          "now" "`$FUNCTION`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "rbac" (vs/jm
        "options" (vs/jm
          "active" false
          "deny" false
          "permissions" (vs/jt)
          "rules" (vs/jm))
        "optspec" (vs/jm)
        "strict" false
        "transport" "none")
      "retry" (vs/jm
        "options" (vs/jm
          "active" false
          "factor" 2
          "maxDelay" 2000
          "minDelay" 50
          "retries" 2
          "statuses" (vs/jt
            408
            425
            429
            500
            502
            503
            504))
        "optspec" (vs/jm
          "jitter" "`$BOOLEAN`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "secrets" (vs/jm
        "options" (vs/jm
          "active" false
          "cache" true
          "exchange" (vs/jm
            "active" false
            "method" "POST"
            "path" "auth/token"
            "refresh" ""
            "request" "refresh_token"
            "response" "access_token"
            "retries" 1
            "statuses" (vs/jt
              401))
          "name" "apikey"
          "providers" (vs/jt))
        "optspec" (vs/jm)
        "strict" false
        "transport" "wrap")
      "streaming" (vs/jm
        "options" (vs/jm
          "active" false
          "chunkDelay" 0
          "chunkSize" 0)
        "optspec" (vs/jm
          "ops" "`$LIST`"
          "sleep" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "telemetry" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "exporter" "`$FUNCTION`"
          "headers" "`$MAP`"
          "idgen" "`$FUNCTION`"
          "now" "`$FUNCTION`")
        "strict" false
        "transport" "none")
      "test" (vs/jm
        "options" (vs/jm
          "active" false)
        "optspec" (vs/jm
          "entity" "`$MAP`"
          "net" "`$MAP`")
        "strict" false
        "transport" "base")
      "timeout" (vs/jm
        "options" (vs/jm
          "active" false
          "ms" 30000)
        "optspec" (vs/jm
          "clearTimer" "`$FUNCTION`"
          "now" "`$FUNCTION`"
          "setTimer" "`$FUNCTION`")
        "strict" false
        "transport" "wrap")
      "validate" (vs/jm
        "options" (vs/jm
          "active" false
          "mode" "throw"
          "request" true
          "response" false
          "strict" false)
        "optspec" (vs/jm
          "mode" (vs/jt
            "`$ONE`"
            (vs/jt
              "`$EXACT`"
              "throw")
            (vs/jt
              "`$EXACT`"
              "report"))
          "onInvalid" "`$FUNCTION`")
        "strict" false
        "transport" "none"))
    "main" (vs/jm
      "name" "Thesmsworks"
      "slug" "thesmsworks"
      "target" "clojure"
      "version" "0.1.2")
    "options" (vs/jm
      "auth" (vs/jm
        "prefix" "")
      "base" "https://api.thesmsworks.co.uk/v1"
      "entity" (vs/jm
        "batch" (vs/jm)
        "batch_message" (vs/jm)
        "credit" (vs/jm)
        "message" (vs/jm)
        "message_message" (vs/jm)
        "message_schedule" (vs/jm)
        "one_time_password" (vs/jm)
        "schedule" (vs/jm)
        "util" (vs/jm))
      "headers" (vs/jm
        "content-type" "application/json"))))

(def feature-plugins
  {})

(def feature-extra
  {"secrets" (fn [] (sdk.feature.secrets/secrets-feature (get feature-plugins "secrets")))})
