;; Thesmsworks SDK: where the credential goes (generated by @voxgig/sdkgen).
;;
;; PART OF THE sdk.core NAMESPACE, not a namespace of its own: core.clj reads
;; this file with `(load "prepare_auth")` at the point u-prepare-auth used to
;; be defined, so oget / ctx-error / client-options-map are already in scope
;; and base-utility-map's `:prepare-auth u-prepare-auth` still resolves.
(in-ns 'sdk.core)

(def HEADER-AUTH "authorization")
(def OPTION-APIKEY "apikey")
(def NOT-FOUND "__NOTFOUND__")

;; The client's auth.name option, when set, replaces the name the API declares.
(defn- prepare-auth-name [options]
  (let [given (vs/getpath options "auth.name")]
    (if (and (string? given) (not= "" given)) (.toLowerCase ^String given java.util.Locale/ROOT) HEADER-AUTH)))

(defn u-prepare-auth [ctx]
  (let [spec (oget ctx :spec)]
    (if (nil? spec) [nil (ctx-error ctx "auth_no_spec" "Expected context spec property to be defined.")]
        (let [headers (oget spec :headers)
              options (client-options-map (oget ctx :client))]
          (if (nil? (vs/getprop options "auth"))
            ;; Public APIs that need no auth omit the options.auth block entirely.
            (do (vs/delprop headers HEADER-AUTH) [spec nil])
            (let [cred (prepare-auth-name options)
                  apikey (vs/getprop options OPTION-APIKEY NOT-FOUND)]
              ;; A credential left under the declared name would travel beside the renamed one.
              (when (not= cred HEADER-AUTH) (vs/delprop headers HEADER-AUTH))
              (if (or (nil? apikey) (and (string? apikey) (or (= apikey NOT-FOUND) (= apikey ""))))
                (vs/delprop headers cred)
                (let [auth-prefix (or (vs/getpath options "auth.prefix") "")
                      apikey-val (if (string? apikey) apikey "")]
                  (.put ^java.util.Map headers cred
                        (if (= auth-prefix "") apikey-val (str auth-prefix " " apikey-val)))))
              [spec nil]))))))
